use crate::err::AppError;
use sqlx::{Pool, Postgres};

pub async fn create_language_codes(pool: &Pool<Postgres>) -> Result<(), AppError> {

    let sql = r#"drop table if exists lups.language_codes;
    CREATE TABLE lups.language_codes (
        code               char(2)    NOT NULL PRIMARY KEY,
      	marc_code          varchar    NULL,
	    lang_name_en       varchar    NULL,
	    lang_name_fr       varchar    NULL,
	    lang_name_de       varchar    NULL,
	    is_major           bool       NULL
    );"#;
    
    sqlx::raw_sql(&sql).execute(pool)
        .await.map_err(|e| AppError::SqlxError(e, sql.to_string()))?;

    let sql = r#"insert into lups.language_codes (code, marc_code,
	    lang_name_en, lang_name_fr, lang_name_de, is_major)
    values
        ('af', 'afr', 'Afrikaans', 'afrikaans', 'Afrikaans', false ),
        ('am', 'amh', 'Amharic', 'amharique', 'Amharisch', false),
        ('ar', 'ara', 'Arabic', 'arabe', 'Arabisch', true),
        ('az', 'aze', 'Azerbaijani', 'azéri', 'Aserbeidschanisch', true),
        ('be', 'bel', 'Belarusian', 'biélorusse', 'Weißrussisch', true),
        ('bg', 'bul', 'Bulgarian', 'bulgare', 'Bulgarisch', true),
        ('bn', 'ben', 'Bengali', 'bengali', 'Bengali', true),
        ('bo', 'tib', 'Tibetan', 'tibétain', 'Tibetisch', false),
        ('br', 'bre', 'Breton', 'breton', 'Bretonisch', false),
        ('bs', 'bos', 'Bosnian', 'bosniaque', 'Bosnisch', true),
        ('ca', 'cat', 'Catalan', 'catalan', 'Katalanisch', false),
        ('ce', 'che', 'Chechen', 'tchétchène', 'Tschetschenisch', false),
        ('co', 'cos', 'Corsican', 'corse', 'Korsisch', false),
        ('cs', 'cze', 'Czech', 'tchèque', 'Tschechisch', true),
        ('cy', 'wel', 'Welsh', 'gallois', 'Kymrisch', false),
        ('da', 'dan', 'Danish', 'danois', 'Dänisch', true),
        ('de', 'ger', 'German', 'allemand', 'Deutsch', true),
        ('el', 'gre', 'Greek', 'grec ', 'Griechisch', true),
        ('en', 'eng', 'English', 'anglais', 'Englisch', true),
        ('eo', 'epo', 'Esperanto', 'espéranto', 'Esperanto', false),
        ('es', 'spa', 'Spanish', 'espagnol', 'Spanisch', true),
        ('et', 'est', 'Estonian', 'estonien', 'Estnisch', true),
        ('eu', 'baq', 'Basque', 'basque', 'Baskisch', false),
        ('fa', 'per', 'Persian', 'persan', 'Persisch', true),
        ('fi', 'fin', 'Finnish', 'finnois', 'Finnisch', true),
        ('fr', 'fre', 'French', 'français', 'Französisch', true),
        ('ga', 'gle', 'Irish Gaelic', 'irlandais', 'Irisch', false),
        ('gd', 'gla', 'Scottish Gaelic', 'gaélique écossais', 'Gälisch-Schottisch', false),
        ('gl', 'glg', 'Galician', 'galicien', 'Galicisch', false),
        ('gu', 'guj', 'Gujarati', 'goudjrati', 'Gujarati-Sprache', true),
        ('ha', 'hau', 'Hausa', 'haoussa', 'Haussa-Sprache', false),
        ('he', 'heb', 'Hebrew', 'hébreu', 'Hebräisch', true),
        ('hi', 'hin', 'Hindi', 'hindi', 'Hindi', true),
        ('hr', 'hrv', 'Croatian', 'croate', 'Kroatisch', true),
        ('hu', 'hun', 'Hungarian', 'hongrois', 'Ungarisch', true),
        ('hy', 'arm', 'Armenian', 'arménien', 'Armenisch', true),
        ('id', 'ind', 'Indonesian', 'indonésien', 'Bahasa Indonesia', true),
        ('is', 'ice', 'Icelandic', 'islandais', 'Isländisch', true),
        ('it', 'ita', 'Italian', 'italien', 'Italienisch', true),
        ('iu', 'iku', 'Inuktitut', 'inuktitut', 'Inuktitut', false),
        ('ja', 'jpn', 'Japanese', 'japonais', 'Japanisch', true),
        ('jv', 'jav', 'Javanese', 'javanais', 'Javanisch', false),
        ('ka', 'geo', 'Georgian', 'géorgien', 'Georgisch', true),
        ('kk', 'kaz', 'Kazakh', 'kazakh', 'Kasachisch', true),
        ('kl', 'kal', 'Greenlandic, Kalaallisut', 'groenlandais', 'Grönländisch', false),
        ('km', 'khm', 'Central Khmer', 'khmer central', 'Kambodschanisch', false),
        ('kn', 'kan', 'Kannada', 'Kannada', 'Kannada', false),
        ('ko', 'kor', 'Korean', 'coréen', 'Koreanisch', true),
        ('ks', 'kas', 'Kashmiri', 'kashmiri', 'Kaschmiri', false),
        ('ku', 'kur', 'Kurdish', 'kurde', 'Kurdisch', false),
        ('la', 'lat', 'Latin', 'latin', 'Latein', false),
        ('lb', 'ltz', 'Luxembourgish', 'luxembourgeois', 'Luxemburgisch', false),
        ('lo', 'lao', 'Lao', 'lao', 'Laotisch', false),
        ('lt', 'lit', 'Lithuanian', 'lituanien', 'Litauisch', true),
        ('lv', 'lav', 'Latvian', 'letton', 'Lettisch', true),
        ('mi', 'mao', 'Maori', 'maori', 'Maori-Sprache', false),
        ('mk', 'mac', 'Macedonian', 'macédonien', 'Makedonisch', false),
        ('ml', 'mal', 'Malayalam', 'malayalam', 'Malayalam', false),
        ('mn', 'mon', 'Mongolian', 'mongol', 'Mongolisch', false),
        ('mr', 'mar', 'Marathi', 'Marathi', 'Marathi', false),
        ('ms', 'may', 'Malay', 'malais', 'Malaiisch', true),
        ('mt', 'mlt', 'Maltese', 'maltais', 'Maltesisch', false),
        ('mu', 'mul', 'Multiple languages', 'multiples langues', 'multipel Sprachen', false),
        ('my', 'bur', 'Burmese', 'birman', 'Birmanisch', true),
        ('ne', 'nep', 'Nepali', 'népalais', 'Nepali', false),
        ('nl', 'dut', 'Dutch', 'néerlandais; flamand', 'Niederländisch', true),
        ('no', 'nor', 'Norwegian', 'norvégien', 'Norwegisch', true),
        ('os', 'oss', 'Ossetian', 'ossète', 'Ossetisch', false),
        ('pa', 'pan', 'Punjabi', 'pendjabi', 'Pandschabi-Sprache', true),
        ('pl', 'pol', 'Polish', 'polonais', 'Polnisch', true),
        ('ps', 'pus', 'Pashto', 'pachto', 'Paschtu', false),
        ('pt', 'por', 'Portuguese', 'portugais', 'Portugiesisch', true),
        ('qu', 'que', 'Quechua', 'quechua', 'Quechua-Sprache', false),
        ('rm', 'roh', 'Romansh', 'romanche', 'Rätoromanisch', false),
        ('ro', 'rum', 'Romanian, Moldavian', 'roumain; moldave', 'Rumänisch', true),
        ('ru', 'rus', 'Russian', 'russe', 'Russisch', true),
        ('rw', 'kin', 'Kinyarwanda', 'kinyarwanda', 'Kinyarwanda', false),
        ('se', 'sme', 'Northern Sami', 'sami du Nord', 'Nordsaamisch', false),
        ('si', 'sin', 'Sinhalese', 'singhalais', 'Singhalesisch', false),
        ('sk', 'slo', 'Slovak', 'slovaque', 'Slowakisch', true),
        ('sl', 'slv', 'Slovenian', 'slovène', 'Slowenisch', true),
        ('sm', 'smo', 'Samoan', 'samoan', 'Samoanisch', false),
        ('sn', 'sna', 'Shona', 'shona', 'Schona-Sprache', false),
        ('so', 'som', 'Somali', 'somali', 'Somali', false),
        ('sq', 'alb', 'Albanian', 'albanais', 'Albanisch', true),
        ('sr', 'srp', 'Serbian', 'serbe', 'Serbisch', true),
        ('sv', 'swe', 'Swedish', 'suédois', 'Schwedisch', true),
        ('sw', 'swa', 'Swahili', 'swahili', 'Swahili', true),
        ('ta', 'tam', 'Tamil', 'tamoul', 'Tamil', false),
        ('te', 'tel', 'Telugu', 'télougou', 'Telugu-Sprache', false),
        ('tg', 'tgk', 'Tajik', 'tadjik', 'Tadschikisch', false),
        ('th', 'tha', 'Thai', 'thaï', 'Thailändisch', true),
        ('tk', 'tuk', 'Turkmen', 'turkmène', 'Turkmenisch', false),
        ('to', 'ton', 'Tongan', 'tongan (Îles Tonga)', 'Tongaisch', false),
        ('tr', 'tur', 'Turkish', 'turc', 'Türkisch', true),
        ('tt', 'tat', 'Tatar', 'tatar', 'Tatarisch', false),
        ('ty', 'tah', 'Tahitian', 'tahitien', 'Tahitisch', false),
        ('uk', 'ukr', 'Ukrainian', 'ukrainien', 'Ukrainisch', true),
        ('un', 'und', 'Undetermined', 'Indéterminée', 'Nicht zu entscheiden', false),
        ('ur', 'urd', 'Urdu', 'ourdou', 'Urdu', true),
        ('uz', 'uzb', 'Uzbek', 'ouszbek', 'Usbekisch', true),
        ('vi', 'vie', 'Vietnamese', 'vietnamien', 'Vietnamesisch', true),
        ('xh', 'xho', 'Xhosa', 'xhosa', 'Xhosa-Sprache', false),
        ('yo', 'yor', 'Yoruba', 'yoruba', 'Yoruba-Sprache', false),
        ('zh', 'chi', 'Chinese', 'chinois', 'Chinesisch', true),
        ('zu', 'zul', 'Zulu', 'zoulou', 'Zulu-Sprache', false);"#;

    sqlx::raw_sql(&sql).execute(pool)
        .await.map_err(|e| AppError::SqlxError(e, sql.to_string()))?;

    Ok(())
}
    
 
pub async fn create_language_scripts(pool: &Pool<Postgres>) -> Result<(), AppError> {

    let sql = r#"drop table if exists lups.language_scripts;
    CREATE TABLE lups.language_scripts (
        code               varchar(4) NOT NULL PRIMARY KEY,
	    unicode_name       varchar    NULL,
	    iso_name           varchar    NULL,
	    directionality     varchar    NULL,
	    num_characters     varchar    NULL,
	    notes              varchar    NULL,
	    hex_start          varchar    NULL,
	    hex_end            varchar    NULL,
	    ascii_start        int4       NULL,
	    ascii_end          int4       NULL
    );"#;
    
    sqlx::raw_sql(&sql).execute(pool)
        .await.map_err(|e| AppError::SqlxError(e, sql.to_string()))?;

    let sql = r#"insert into lups.language_scripts (code, unicode_name, iso_name, directionality,
	    num_characters, notes, hex_start, hex_end, ascii_start, ascii_end)
    values
    ('Adlm', 'Adlam', 'Adlam', 'RtL', 88, 'Used in parts of West and Central Africa', '1E900', '1E95F', 125184, 125279),
    ('Arab', 'Arabic', 'Arabic', 'RtL', 1365, null, '0600', '06FF', 1536, 1791),
    ('Armn', 'Armenian', 'Armenian', 'LtR', 96, null, '0530', '058F', 1328, 1423),
    ('Bali', 'Balinese', 'Balinese', 'LtR', 124, null, '1B00', '1B7F', 6912, 7039),
    ('Batk', 'Batak', 'Batak', 'LtR', 56, 'Used in Indonesia', '1BC0', '1BFF', 7104, 7167),
    ('Beng', 'Bengali', 'Bengali (Bangla)', 'LtR', 96, null, '0980', '09FF', 2432, 2559),
    ('Bopo', 'Bopomofo', 'Bopomofo', 'LtR', 77, 'A Chinese transliteration system for Mandarin Chinese and related languages, mostly used in Taiwan', '3100', '312F', 12544, 12591),
    ('Bugi', 'Buginese', 'Buginese', 'LtR', 30, 'Used in parts of Indonesia', '1A00', '1A1F', 6656, 6687),
    ('Buhd', 'Buhid', 'Buhid', 'LtR', 20, 'Used in parts of the Philippines', '1740', '175F', 5952, 5983),
    ('Cans', 'Canadian Aboriginal', 'Unified Canadian Aboriginal Syllabics', 'LtR', 726, 'Used in Inuit and related languages', '1400', '167F', 5120, 5759),
    ('Cakm', 'Chakma', 'Chakma', 'LtR', 71, 'Used in parts of India and Bangla Desh', '11100', '1114F', 69888, 69967),
    ('Cham', 'Cham', 'Cham', 'LtR', 83, 'Used in parts of Vietnam and Cambodia', 'AA00', 'AA5F', 43520, 43615),
    ('Zyyy', 'Common', 'Code for undetermined script', 'n/a', null, null, null, null, null, null),
    ('Cyrl', 'Cyrillic', 'Cyrillic', 'LtR', 443, null, '0400', '04FF', 1024, 1279),
    ('Deva', 'Devanagari', 'Devanagari (Nagari)', 'LtR', 154, 'Used in parts of India, including for Hindi and Marathi', '0900', '097F', 2304, 2431),
    ('Ethi', 'Ethiopic', 'Ethiopic (Geʻez)', 'LtR', 523, 'Used for Amharic and related languages in and around Ethiopa', '1200', '137C', 4608, 4988),
    ('Geor', 'Georgian', 'Georgian (Mkhedruli and Mtavruli)', 'LtR', 173, null, '10A0', '10FF', 4256, 4351),
    ('Geok', 'Georgian', 'Khutsuri (Asomtavruli and Nuskhuri)', 'LtR', null, 'Three different related scripts', null, null, null, null),
    ('Grek', 'Greek', 'Greek', 'LtR', 518, null, '0370', '03FF', 880, 1023),
    ('Gujr', 'Gujarati', 'Gujarati', 'LtR', 91, null, '0A80', '0AFF', 2688, 2815),
    ('Gong', 'Gunjala Gondi', 'Gunjala Gondi', 'LtR', 63, 'Used in parts of India', '11D60', '11DAF', 73056, 73135),
    ('Guru', 'Gurmukhi', 'Gurmukhi', 'LtR', 80, 'Used in parts of India (mainly Punjab)', '0A00', '0A7F', 2560, 2687),
    ('Hani', 'Han', 'Han (Hanzi, Kanji, Hanja)', 'TtB, RtL', 94215, 'Chinese characters (including those in Japanese Kanji)', '4E00', '9FFF', 19968, 40959),
    ('Jpan', 'Han, Hiragana, Katakana', 'Japanese', 'n/a', null, 'Alias for Han + Hiragana + Katakana', null, null, null, null),
    ('Hang', 'Hangul', 'Hangul (Hangŭl, Hangeul)', 'LtR, VRtL', 11739, 'The Korean alphabet', 'AC00', 'D7AF', 44032, 55215),
    ('Rohg', 'Hanifi Rohingya', 'Hanifi Rohingya', 'RtL', 50, 'Used by the Rohingya people in Burma', '10D00', '10D3F', 68864, 68927),
    ('Hano', 'Hanunoo', 'Hanunoo (Hanunóo)', 'LtR, BtT', 21, 'Used in parts of the Philippines', '1720', '173F', 5920, 5951),
    ('Hebr', 'Hebrew', 'Hebrew', 'RtL', 134, null, '0590', '05FF', 1424, 1535),
    ('Hira', 'Hiragana', 'Hiragana', 'VRtL, LtR', 380, 'Used in Japan for verbs, words not covered by Kanji or as a more informal form than Kanji', '3040', '309F', 12352, 12447),
    ('Java', 'Javanese', 'Javanese', 'LtR', 90, null, 'A980', 'A9DF', 43392, 43487),
    ('Knda', 'Kannada', 'Kannada', 'LtR', 90, 'Used in parts of India (mainly the South)', '0C80', '0CFF', 3200, 3327),
    ('Kana', 'Katakana', 'Katakana', 'VRtL, LtR', 320, 'Used in Japan for loan words and many scientific, technical terms', '30A0', '30FF', 12448, 12543),
    ('Khmr', 'Khmer', 'Khmer', 'LtR', 146, 'Used in Cambodia', '1780', '17FF', 6016, 6143),
    ('Sind', 'Khudawadi', 'Khudawadi, Sindhi', 'LtR', 69, 'Used in parts of India', '112B0', '112FF', 70320, 70399),
    ('Laoo', 'Lao', 'Lao', 'LtR', 82, 'Used in Laos', '0E80', '0EFF', 3712, 3839),
    ('Latn', 'Latin', 'Latin', 'LtR', 1475, null, '0', '02FF', 0, 767),
    ('Lepc', 'Lepcha', 'Lepcha (Róng)', 'LtR', 74, 'Used in parts of India, Tibet', '1C00', '1C4F', 7168, 7247),
    ('Limb', 'Limbu', 'Limbu', 'LtR', 68, 'Used in parts of India, Tibet', '1900', '194F', 6400, 6479),
    ('Mlym', 'Malayalam', 'Malayalam', 'LtR', 118, 'Used in parts of India (Kerala)', '0D00', '0D7F', 3328, 3455),
    ('Mtei', 'Meetei Mayek', 'Meitei Mayek (Meithei, Meetei)', 'LtR', 79, 'Used in parts of India', 'ABC0', 'ABFF', 43968, 44031),
    ('Mend', 'Mende Kikakui', 'Mende Kikakui', 'RtL', 213, 'Used  in Sierra Leone', '1E800', '1E8DF', 124928, 125151),
    ('Plrd', 'Miao', 'Miao (Pollard)', 'LtR', 149, 'Used in parts of China', '16F00', '16F9F', 93952, 94111),
    ('Mong', 'Mongolian', 'Mongolian', 'VLtR, LtR', 168, null, '1800', '18AF', 6144, 6319),
    ('Mroo', 'Mro', 'Mro, Mru', 'LtR', 43, 'Used in parts of Myanmar and Bangla Desh', '16A40', '16A6F', 92736, 92783),
    ('Mymr', 'Myanmar', 'Myanmar (Burmese)', 'LtR', 223, null, '1000', '109F', 4096, 4255),
    ('Talu', 'New Tai Lue', 'New Tai Lue', 'LtR', 83, 'Used in parts of China and its southern neighbours', '1980', '19DF', 6528, 6623),
    ('Newa', 'Newa', 'Newa, Newar, Newari, Nepāla lipi', 'LtR', 97, 'Used in Nepal', '11400', '1147F', 70656, 70783),
    ('Nkoo', 'NKo', 'N’Ko', 'RtL', 62, 'Used in parts of West Africa', '07C0', '07FF', 1984, 2047),
    ('Olck', 'Ol Chiki', 'Ol Chiki (Ol Cemet’, Ol, Santali)', 'LtR', 48, 'Used in parts of India', '1C50', '1C7F', 7248, 7295),
    ('Orya', 'Oriya', 'Oriya (Odia)', 'LtR', 91, 'Used in parts of India', '0B00', '0B7F', 2816, 2943),
    ('Hmng', 'Pahawh Hmong', 'Pahawh Hmong', 'LtR', 127, 'Used in parts of China and its southern neighbours', '16B00', '16B8F', 92928, 93071),
    ('Pauc', 'Pau Cin Hau', 'Pau Cin Hau', 'LtR', 57, 'Used in parts of Burma', '11AC0', '11AFF', 72384, 72447),
    ('Saur', 'Saurashtra', 'Saurashtra', 'LtR', 82, 'Used in parts of India', 'A880', 'A8DF', 43136, 43231),
    ('Sinh', 'Sinhala', 'Sinhala', 'LtR', 111, 'Used in Sri Lanka', '0D80', '0DFF', 3456, 3583),
    ('Sund', 'Sundanese', 'Sundanese', 'LtR', 72, 'Used in parts of Indonesia', '1B80', '1BBF', 7040, 7103),
    ('Tglg', 'Tagalog', 'Tagalog (Baybayin, Alibata)', 'LtR', 23, 'Used in parts of the Philippines', '1700', '171F', 5888, 5919),
    ('Tagb', 'Tagbanwa', 'Tagbanwa', 'LtR', 18, 'Used in parts of the Philippines', '1760', '177F', 5984, 6015),
    ('Tale', 'Tai Le', 'Tai Le', 'LtR', 35, 'Used in parts of China', '1950', '197F', 6480, 6527),
    ('Lana', 'Tai Tham', 'Tai Tham (Lanna)', 'LtR', 127, 'Used in parts of Thailand', '1A20', '1AAF', 6688, 6831),
    ('Tavt', 'Tai Viet', 'Tai Viet', 'LtR', 72, 'Used in parts of Thailand', 'AA80', 'AADF', 43648, 43743),
    ('Taml', 'Tamil', 'Tamil', 'LtR', 123, 'Used in parts of India', '0B80', '0BFF', 2944, 3071),
    ('Telu', 'Telugu', 'Telugu', 'LtR', 100, 'Used in parts of India', '0C00', '0C7F', 3072, 3199),
    ('Thaa', 'Thaana', 'Thaana', 'RtL', 50, 'Used in the Maldives', '0780', '07BF', 1920, 1983),
    ('Thai', 'Thai', 'Thai', 'LtR', 86, '', '0E00', '0E7F', 3584, 3711),
    ('Tibt', 'Tibetan', 'Tibetan', 'LtR', 207, '', '0F00', '0FFF', 3840, 4095),
    ('Wara', 'Warang Citi', 'Warang Citi (Varang Kshiti)', 'LtR', 84, 'Used in parts of India', '118A0', '118FF', 71840, 71935),
    ('Yiii', 'Yi', 'Yi', 'LtR', 1220, 'Used in parts of China', 'A000', 'A48F', 40960, 42127);"#;

    sqlx::raw_sql(&sql).execute(pool)
        .await.map_err(|e| AppError::SqlxError(e, sql.to_string()))?;

    Ok(())
}